### ISSUE TITLE
Example - Build Error

### ISSUE THREAD

**Issue by blockcowboy** [tesseract-one/Tesseract.swift#2]
DApp/AppCore.swift
No such module CApp 

Was there a dependency setup I missed in Readme?

Also, can Tesseract.swift be used for MacOS?

**Comment by ypopovych** [comment]
`CApp` will be created at the first build. It is a Rust module.

For now `Tesseract.swift` is iOS only because it has only IPC transport for iOS. We will add more transports soon, some of them can be cross-platform, or macOS related

**Comment by blockcowboy** [comment]
> `CApp` will be created at the first build. It is a Rust module.
> 
> For now `Tesseract.swift` is iOS only because right now it has only IPC transport for iOS. We will add more transports soon, some of them can be cross-platform, or macOS related

It is not building. 

![image](https://user-images.githubusercontent.com/39525654/222241941-98058753-4678-4e46-a775-2757f9f0610e.png)

**Comment by ypopovych** [comment]
Could you, please, check the error in the build log and post it here?
It should return an error from the build script/cargo if something is not working.

**Comment by blockcowboy** [comment]
> Could you, please, check the error in the build log and post it here?
> It should return an error from the build script/cargo if something is not working.

#1 I added something to catch the build error, It was not showing up in build log
**exec > ${PROJECT_DIR}/prebuild.log 2>&1**
exec bash ${SRCROOT}/rust/xcode_build_step.sh CApp app

#2 got this error:

   Compiling tesseract-protocol-test v0.1.0 (https://github.com/tesseract-one/Tesseract.rs?branch=master#b4856f64)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> ~/.cargo/git/checkouts/tesseract.rs-30a587f160fe3f19/b4856f6/protocols/test/src/lib.rs:17:1
   |
17 | #![feature(async_closure)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `tesseract-protocol-test` due to previous error

**Comment by blockcowboy** [comment]
This is the build log which did not show error above.

![image](https://user-images.githubusercontent.com/39525654/222251750-ef7f7059-bb17-445b-b767-45ad026f2e6a.png)

**Comment by ypopovych** [comment]
You are using `stable` rust. The project uses some unstable features. I pushed the commit with `rust-toolchain` files which should enforce cargo to use `nightly` rust (it should be installed on your machine).

**Comment by blockcowboy** [comment]
> You are using `stable` rust. The project uses some unstable features. I pushed the commit with `rust-toolchain` files which should enforce cargo to use `nightly` rust (it should be installed on your machine).

I cloned the updated. I got 221 errors. 
I had to run:
rustup target add x86_64-apple-ios

Then ;)

![image](https://user-images.githubusercontent.com/39525654/222257162-1b036d45-7183-4920-a28d-5aec7feec18b.png)

**Comment by blockcowboy** [comment]
See above compiled.
