### ISSUE TITLE
Demo App Error - Wallet Not Installed

### ISSUE THREAD

**Issue by blockcowboy** [tesseract-one/Tesseract.swift#3]
Compiled demo app. Did not see dependency for Wallet App in readme.

![image](https://user-images.githubusercontent.com/39525654/222258621-4512bd27-0765-4711-90d8-d1173cae6590.png)

**Comment by ypopovych** [comment]
But it shows a proper message. If you had a wallet installed you didn't see it. It can check the availability of the needed wallet on the device

**Comment by blockcowboy** [comment]
> But it shows a proper message. If you had a wallet installed you didn't see it. It can check the availability of the needed wallet on the device

No wallet on simulator. Was it supposed to load your demo wallet?

![image](https://user-images.githubusercontent.com/39525654/222259910-6d36df0f-714e-4b62-8fbf-b88cfd06a55e.png)

**Comment by ypopovych** [comment]
you can build and run the `Wallet` target on the same simulator device. It will work after that

**Comment by blockcowboy** [comment]
I got the wallet to run. 

Do you have any other transaction examples or guides for using with local chain contract?

let signed = Arc::clone(&service).sign_transaction("testTransaction");

![image](https://user-images.githubusercontent.com/39525654/222263026-d463be55-97fc-4a9a-a8ff-e2a8961859c6.png)

**Comment by ypopovych** [comment]
We are working right now on a more sophisticated example with a SmartContract call on Polkadot Testnet.

Wallet which can sign Polkadot Transactions: https://github.com/tesseract-one/dev-wallet
SmartContrract chat application: https://github.com/tesseract-one/polkachat.rs

Examples in this repository work on the `test` protocol and are created for transport testing.

**Comment by blockcowboy** [comment]
I will have to wait until you have some submit transaction examples. Not clear how I can do it using current state of library. It will be great when there is something viable for Swift/iOS/Mac and Android/Kotlin. This a challenge with all chains.

**Comment by ypopovych** [comment]
They will be not inside this library, though. This is an SDK that allows a connection between dApp and Wallet. It replaces the `Signer` part only. For transaction building or submitting you will need a network-related SDK which can be connected to this SDK.

**Comment by ypopovych** [comment]
We also working on the Substrate/Polkadot Swift library. I think if you want to build transactions in Swift it will be more useful to you.

https://github.com/tesseract-one/Substrate.swift

WIP though, but should have the first alpha version soon
